#!/bin/sh

# Copyright (c) 2011, Matt Goatcher
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

SORT=`which sort`
UNIQ=`which uniq`
COMM=`which comm`
MKFIFO="mkfifo"
MKTEMPDIR="mktemp -d -t intersect"
RM="rm -f"
RMDIR="rmdir"

function usage() {
	cat <<EOF
Usage: $0 [-i] file1 file2
Takes the intersection of file1 and file2
EOF
	exit 0
}

while getopts ":ih" opt; do
	case $opt in

	i ) UNIQOPTS="-i" && COMMOPTS="-i" ;;
	h ) usage ;;
	\?) usage ;;

	esac
done

shift $(($OPTIND - 1))

if [ $# -lt 2 ]; then
	echo "Must specify at least 2 files"
	usage
fi

if [ $# -gt 2 ]; then
	echo "Only 2 files can be intersected currently"
	usage
fi

TMPDIR=`$MKTEMPDIR` || exit 1
FILE1="$TMPDIR/file1"
FILE2="$TMPDIR/file2"

$SORT "$1" | $UNIQ $UNIQUEOPTS > "$FILE1"
$SORT "$2" | $UNIQ $UNIQUEOPTS > "$FILE2"

$COMM $COMMOPTS -12 "$FILE1" "$FILE2"

$RM "$FILE1"
$RM "$FILE2"
$RMDIR "$TMPDIR"
